### ISSUE TITLE
chrome version

### ISSUE THREAD

**Issue by urfausto** [fredden/bookmark-301-updater#1]
it seems not working anymore since few months. it was working correctly earlier... it's unfortunate since it's the only extension of its kind in the webstore.

**Comment by fredden** [comment]
Thanks for reaching out. I've just tested now with Google Chrome version 80.0.3987.106 using a fresh profile. It appears to be working as far as I can tell. What version of Chrome are you using, and do you have an example link that's not updating for you?

**Comment by urfausto** [comment]
i'm on vivaldi 64bit
i noticed the extension was failing with this website: https://cb01.lat because it changes domain quite often. this one also: https://altadefinizione.style
at some point they didn't automatically redirected me anymore and remained still on the inactive page...

**Comment by fredden** [comment]
Those URLs are returning 403 & 503 respectively. The extension specifically looks for permanent redirects (301 or 308).

**Comment by urfausto** [comment]
oh ok, my bad then. thanks for the time.
